#!/usr/bin/env bash

docker rm -f $(docker ps -a -q)

#docker start meeseeks-db-redis0 meeseeks-db-redis1 meeseeks-db-redis2

docker pull redis
docker run -v ${PWD}/etc/dev-test/redis.conf:/usr/local/etc/redis.conf --name meeseeks-db-redis0 -p 26269:6379 -d redis redis-server /usr/local/etc/redis.conf
docker run -v ${PWD}/etc/dev-test/redis.conf:/usr/local/etc/redis.conf --name meeseeks-db-redis1 -p 26279:6379 -d redis redis-server /usr/local/etc/redis.conf
docker run -v ${PWD}/etc/dev-test/redis.conf:/usr/local/etc/redis.conf --name meeseeks-db-redis2 -p 26289:6379 -d redis redis-server /usr/local/etc/redis.conf

lein midje